// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/compare": {
            "post": {
                "description": "查询2个Excel文件中列的重复数据",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "summary": "查询2个Excel文件中列的重复数据",
                "parameters": [
                    {
                        "type": "file",
                        "description": "文件1",
                        "name": "file1",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "文件2",
                        "name": "file2",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文件1数据是从第几行开始",
                        "name": "line1",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文件1要对比第几列",
                        "name": "column1",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文件2数据是从第几行开始",
                        "name": "line2",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "文件2要对比第几列",
                        "name": "column2",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":200,\"data\":{},\"msg\":\"OK\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "{\"code\":401,\"data\":{},\"msg\":\"UNAUTHORIZED\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "{\"code\":500,\"data\":{},\"msg\":\"SERVERERROR\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "80002": {
                        "description": "{\"code\":80002,\"data\":{},\"msg\":\"PARAMCHECKFAILED\"}",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "80003": {
                        "description": "{\"code\":80003,\"data\":{},\"msg\":\"DATABASEOPFAILED\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
